### ISSUE TITLE
Help with error

### ISSUE THREAD

**Issue by ryanballa** [anencore94/clubhouse-github-action#14]
Hi, I'm seeing this error. Any insights what might be causing it would be helpful.

`----------Sending github api----------
11
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
12
    conn = connection.create_connection(
13
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
14
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
15
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
16
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
17
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:
20

21
Traceback (most recent call last):
22
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
23
    httplib_response = self._make_request(
24
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
25
    self._validate_conn(conn)
26
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
27
    conn.connect()
28
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
29
    conn = self._new_conn()
30
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
31
    raise NewConnectionError(
32
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f907bc399a0>: Failed to establish a new connection: [Errno -2] Name or service not known
33

34
During handling of the above exception, another exception occurred:
35

36
Traceback (most recent call last):
37
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
38
    resp = conn.urlopen(
39
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
40
    retries = retries.increment(
41
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
42
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
43
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.app.shortcut.io', port=443): Max retries exceeded with url: /api/v3/stories/5568 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f907bc399a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
44

45
During handling of the above exception, another exception occurred:
46

47
Traceback (most recent call last):
48
  File "/app/main.py", line 114, in <module>
49
    res = requests.put(
50
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 134, in put
51
    return request('put', url, data=data, **kwargs)
52
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
53
    return session.request(method=method, url=url, **kwargs)
54
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
55
    resp = self.send(prep, **send_kwargs)
56
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
57
    r = adapter.send(request, **kwargs)
58
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
59
    raise ConnectionError(e, request=request)
60
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.app.shortcut.io', port=443): Max retries exceeded with url: /api/v3/stories/5568 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f907bc399a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
`

**Comment by anencore94** [comment]
Hi @ryanballa :) Thanks for raising this issue!

I guess you might use this action version less than or equal to v2.0.3
I think such error was fixed in #13
